2022-05-06 14:09:25 INFO run.py:219 GNS3 server version 2.2.31
2022-05-06 14:09:25 INFO run.py:221 Copyright (c) 2007-2022 GNS3 Technologies Inc.
2022-05-06 14:09:25 INFO run.py:224 Config file /home/barbarik/.config/GNS3/2.2/gns3_server.conf loaded
2022-05-06 14:09:25 WARNING run.py:230 Local mode is enabled. Beware, clients will have full control on your filesystem
2022-05-06 14:09:25 INFO run.py:237 HTTP authentication is enabled with username 'admin'
2022-05-06 14:09:25 INFO run.py:243 Running with Python 3.10.4 and has PID 22890
2022-05-06 14:09:25 INFO run.py:79 Current locale is en_GB.UTF-8
2022-05-06 14:09:25 INFO web_server.py:318 Starting server on localhost:3080
2022-05-06 14:09:25 INFO __init__.py:63 Load controller configuration file /home/barbarik/.config/GNS3/2.2/gns3_controller.conf
2022-05-06 14:09:25 INFO __init__.py:67 Controller is starting
2022-05-06 14:09:25 INFO compute.py:64 Create compute local
2022-05-06 14:09:25 INFO compute.py:364 Connecting to compute 'local'
2022-05-06 14:09:25 INFO web_log.py:206 ::1 [06/May/2022:08:39:25 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 553 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:25 INFO web_log.py:206 ::1 [06/May/2022:08:39:25 +0000] "GET /v2/version HTTP/1.1" 200 228 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:25 INFO notification_handler.py:50 New client has connected to compute WebSocket
2022-05-06 14:09:25 INFO compute.py:434 Connected to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2022-05-06 14:09:25 INFO web_log.py:206 ::1 [06/May/2022:08:39:25 +0000] "GET /v2/version HTTP/1.1" 200 228 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:25 INFO notification_handler.py:73 New client has connected to controller WebSocket
2022-05-06 14:09:25 INFO web_log.py:206 ::1 [06/May/2022:08:39:25 +0000] "GET /v2/templates HTTP/1.1" 200 2502 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:25 INFO web_log.py:206 ::1 [06/May/2022:08:39:25 +0000] "GET /v2/appliances?symbol_theme=Classic HTTP/1.1" 200 805727 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:25 INFO web_log.py:206 ::1 [06/May/2022:08:39:25 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:25 INFO web_log.py:206 ::1 [06/May/2022:08:39:25 +0000] "GET /v2/projects HTTP/1.1" 200 2056 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:25 INFO web_log.py:206 ::1 [06/May/2022:08:39:25 +0000] "GET /v2/projects HTTP/1.1" 200 2056 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:46 INFO project.py:78 Project 86b0b48b-bba8-4986-9eae-8964d865c47a with path '/home/barbarik/GNS3/projects/aishani' created
2022-05-06 14:09:46 WARNING project_manager.py:96 Only 9.20% or less of free disk space detected in "/home/barbarik/GNS3/projects/aishani" on "firefly"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects HTTP/1.1" 201 303 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO __init__.py:303 Creating new hypervisor localhost:57429 with working directory /home/barbarik/GNS3/projects/aishani/project-files/dynamips
2022-05-06 14:09:46 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i1_log.txt', '-H', 'localhost:57429']
2022-05-06 14:09:46 INFO hypervisor.py:129 Dynamips process logging to /home/barbarik/GNS3/projects/aishani/project-files/dynamips/dynamips_i1_stdout.txt
2022-05-06 14:09:46 INFO hypervisor.py:136 Dynamips process started PID=23355
2022-05-06 14:09:46 INFO __init__.py:305 Hypervisor localhost:57429 has successfully started
2022-05-06 14:09:46 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:57429 after 0.3216 seconds
2022-05-06 14:09:46 INFO ethernet_switch.py:187 Ethernet switch "198.16.0.1" [0dab2800-35cb-4361-884b-2862bcc9bfef] has been created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes HTTP/1.1" 201 1565 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO __init__.py:303 Creating new hypervisor localhost:60949 with working directory /home/barbarik/GNS3/projects/aishani/project-files/dynamips
2022-05-06 14:09:46 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i2_log.txt', '-H', 'localhost:60949']
2022-05-06 14:09:46 INFO hypervisor.py:129 Dynamips process logging to /home/barbarik/GNS3/projects/aishani/project-files/dynamips/dynamips_i2_stdout.txt
2022-05-06 14:09:46 INFO hypervisor.py:136 Dynamips process started PID=23371
2022-05-06 14:09:46 INFO __init__.py:305 Hypervisor localhost:60949 has successfully started
2022-05-06 14:09:46 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:60949 after 0.0109 seconds
2022-05-06 14:09:46 INFO ethernet_switch.py:187 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93] has been created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes HTTP/1.1" 201 1566 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO __init__.py:303 Creating new hypervisor localhost:38523 with working directory /home/barbarik/GNS3/projects/aishani/project-files/dynamips
2022-05-06 14:09:46 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i3_log.txt', '-H', 'localhost:38523']
2022-05-06 14:09:46 INFO hypervisor.py:129 Dynamips process logging to /home/barbarik/GNS3/projects/aishani/project-files/dynamips/dynamips_i3_stdout.txt
2022-05-06 14:09:46 INFO hypervisor.py:136 Dynamips process started PID=23387
2022-05-06 14:09:46 INFO __init__.py:305 Hypervisor localhost:38523 has successfully started
2022-05-06 14:09:46 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:38523 after 0.0120 seconds
2022-05-06 14:09:46 INFO ethernet_switch.py:187 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103] has been created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes HTTP/1.1" 201 1565 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO __init__.py:303 Creating new hypervisor localhost:34403 with working directory /home/barbarik/GNS3/projects/aishani/project-files/dynamips
2022-05-06 14:09:46 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i4_log.txt', '-H', 'localhost:34403']
2022-05-06 14:09:46 INFO hypervisor.py:129 Dynamips process logging to /home/barbarik/GNS3/projects/aishani/project-files/dynamips/dynamips_i4_stdout.txt
2022-05-06 14:09:46 INFO hypervisor.py:136 Dynamips process started PID=23403
2022-05-06 14:09:46 INFO __init__.py:305 Hypervisor localhost:34403 has successfully started
2022-05-06 14:09:46 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:34403 after 0.0123 seconds
2022-05-06 14:09:46 INFO ethernet_switch.py:187 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d] has been created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes HTTP/1.1" 201 1566 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.2 [af6a6809-6718-4867-8d5f-22d094f254f7] created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 580 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.3 [635346da-38c1-483d-92bb-3f00cd57af1c] created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 580 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.6 [e3ef85ee-96c7-4e01-8601-a0e4df1246c7] created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 580 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.7 [68885b97-1f1a-48a2-b23a-482b60571460] created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 580 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.8 [71c3a279-3e62-4502-a66f-575a3c1d71a9] created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 580 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.27 [e2993d66-e411-4303-b6db-8af0aeb31c01] created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.26 [bfa31ea6-fddd-49d7-9888-ff20563e92c1] created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.25 [8e6346e2-24a5-49bd-9a6f-1de3884ad63a] created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "GET /v2/computes HTTP/1.1" 200 1021 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.24 [33bc1a19-ff1e-4f57-bd82-4573385cb39b] created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.21 [3f495037-4a81-40bd-bcab-e3d67cb4f5e0] created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.20 [d21636fc-fa63-4777-9577-b2835249eac8] created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.19 [64af328b-55e7-440a-85da-f8fbb25223ba] created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.18 [977096cf-ce03-4a78-8849-69e198f875af] created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.17 [0e72f780-c170-4138-9ea5-b8a1a17a17e3] created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.16 [30827c6b-655c-457f-b522-f27f5dba2fce] created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO base_node.py:282 VPCS: 198.16.0.15 [6e7a02e8-e925-4c05-a9f0-0e442cff63e3] created
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes HTTP/1.1" 201 581 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO __init__.py:303 Creating new hypervisor localhost:34715 with working directory /home/barbarik/GNS3/projects/aishani/project-files/dynamips
2022-05-06 14:09:46 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i5_log.txt', '-H', 'localhost:34715']
2022-05-06 14:09:46 INFO hypervisor.py:129 Dynamips process logging to /home/barbarik/GNS3/projects/aishani/project-files/dynamips/dynamips_i5_stdout.txt
2022-05-06 14:09:46 INFO hypervisor.py:136 Dynamips process started PID=23419
2022-05-06 14:09:46 INFO __init__.py:305 Hypervisor localhost:34715 has successfully started
2022-05-06 14:09:46 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:34715 after 0.0107 seconds
2022-05-06 14:09:46 INFO ethernet_hub.py:97 Ethernet hub "198.16.0.0" [291f188c-98a7-4e5e-bfac-e00e19780bbd] has been created
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_hub/nodes HTTP/1.1" 201 1088 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.1" [0dab2800-35cb-4361-884b-2862bcc9bfef]: NIO udp-1fb19b27-9837-4356-9490-b07996b9f5f8 bound to port 0
2022-05-06 14:09:46 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.1" [0dab2800-35cb-4361-884b-2862bcc9bfef]: port 0 set as an access port in VLAN 1
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0dab2800-35cb-4361-884b-2862bcc9bfef/adapters/0/ports/0/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO vpcs_vm.py:376 VPCS "198.16.0.2" [af6a6809-6718-4867-8d5f-22d094f254f7]: NIO UDP added to port 0
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/af6a6809-6718-4867-8d5f-22d094f254f7/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.1" [0dab2800-35cb-4361-884b-2862bcc9bfef]: NIO udp-332995f8-5ba5-4b0d-bdb2-e277a563a6f3 bound to port 1
2022-05-06 14:09:46 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.1" [0dab2800-35cb-4361-884b-2862bcc9bfef]: port 1 set as an access port in VLAN 1
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0dab2800-35cb-4361-884b-2862bcc9bfef/adapters/0/ports/1/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO vpcs_vm.py:376 VPCS "198.16.0.3" [635346da-38c1-483d-92bb-3f00cd57af1c]: NIO UDP added to port 0
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/635346da-38c1-483d-92bb-3f00cd57af1c/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103]: NIO udp-2b94ebf2-81ef-4b35-8b71-9ab920cd777b bound to port 0
2022-05-06 14:09:46 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103]: port 0 set as an access port in VLAN 1
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/af19e45f-67d3-439a-8b19-b50f30296103/adapters/0/ports/0/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO vpcs_vm.py:376 VPCS "198.16.0.6" [e3ef85ee-96c7-4e01-8601-a0e4df1246c7]: NIO UDP added to port 0
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/e3ef85ee-96c7-4e01-8601-a0e4df1246c7/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103]: NIO udp-032c58ed-2fb5-4e90-8305-44147573226f bound to port 1
2022-05-06 14:09:46 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103]: port 1 set as an access port in VLAN 1
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/af19e45f-67d3-439a-8b19-b50f30296103/adapters/0/ports/1/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO vpcs_vm.py:376 VPCS "198.16.0.7" [68885b97-1f1a-48a2-b23a-482b60571460]: NIO UDP added to port 0
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/68885b97-1f1a-48a2-b23a-482b60571460/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103]: NIO udp-f1e64c89-2af7-4447-83d1-0630d2f4cd03 bound to port 2
2022-05-06 14:09:46 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103]: port 2 set as an access port in VLAN 1
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/af19e45f-67d3-439a-8b19-b50f30296103/adapters/0/ports/2/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO vpcs_vm.py:376 VPCS "198.16.0.8" [71c3a279-3e62-4502-a66f-575a3c1d71a9]: NIO UDP added to port 0
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/71c3a279-3e62-4502-a66f-575a3c1d71a9/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: NIO udp-2e9a4652-ffc2-41a3-8fa0-af0fb0f1dbb9 bound to port 0
2022-05-06 14:09:46 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: port 0 set as an access port in VLAN 1
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/451f9b68-0a39-4975-8f9c-c47d48e7ed93/adapters/0/ports/0/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO vpcs_vm.py:376 VPCS "198.16.0.27" [e2993d66-e411-4303-b6db-8af0aeb31c01]: NIO UDP added to port 0
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/e2993d66-e411-4303-b6db-8af0aeb31c01/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:46 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: NIO udp-994ad7af-379d-420c-9046-965ee15bf08c bound to port 1
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: port 1 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/451f9b68-0a39-4975-8f9c-c47d48e7ed93/adapters/0/ports/1/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.26" [bfa31ea6-fddd-49d7-9888-ff20563e92c1]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/bfa31ea6-fddd-49d7-9888-ff20563e92c1/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: NIO udp-573980db-8006-428a-80a1-3fc5e415eaa8 bound to port 2
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: port 2 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/451f9b68-0a39-4975-8f9c-c47d48e7ed93/adapters/0/ports/2/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.25" [8e6346e2-24a5-49bd-9a6f-1de3884ad63a]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/8e6346e2-24a5-49bd-9a6f-1de3884ad63a/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: NIO udp-13ac1909-000f-46a7-b684-02b64bea66bc bound to port 3
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: port 3 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/451f9b68-0a39-4975-8f9c-c47d48e7ed93/adapters/0/ports/3/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.24" [33bc1a19-ff1e-4f57-bd82-4573385cb39b]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/33bc1a19-ff1e-4f57-bd82-4573385cb39b/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: NIO udp-95e78abd-8e11-4b63-8f1f-11e453afb595 bound to port 0
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: port 0 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/adapters/0/ports/0/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.21" [3f495037-4a81-40bd-bcab-e3d67cb4f5e0]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/3f495037-4a81-40bd-bcab-e3d67cb4f5e0/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: NIO udp-f40fb19d-66c1-4354-a950-2b7eaf96e9b3 bound to port 1
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: port 1 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/adapters/0/ports/1/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.20" [d21636fc-fa63-4777-9577-b2835249eac8]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/d21636fc-fa63-4777-9577-b2835249eac8/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: NIO udp-c54b2f31-752a-403f-88c6-ab2844acb593 bound to port 2
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: port 2 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/adapters/0/ports/2/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.19" [64af328b-55e7-440a-85da-f8fbb25223ba]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/64af328b-55e7-440a-85da-f8fbb25223ba/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: NIO udp-77adc818-fc2e-422c-9716-169dc538c119 bound to port 3
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: port 3 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/adapters/0/ports/3/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.18" [977096cf-ce03-4a78-8849-69e198f875af]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/977096cf-ce03-4a78-8849-69e198f875af/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: NIO udp-6070bbed-c6f4-4ed6-b0c6-3435aab42351 bound to port 4
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: port 4 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/adapters/0/ports/4/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.17" [0e72f780-c170-4138-9ea5-b8a1a17a17e3]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/0e72f780-c170-4138-9ea5-b8a1a17a17e3/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: NIO udp-cad17858-a42a-4cc2-b0f1-3003ec674275 bound to port 5
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: port 5 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/adapters/0/ports/5/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.16" [30827c6b-655c-457f-b522-f27f5dba2fce]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/30827c6b-655c-457f-b522-f27f5dba2fce/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: NIO udp-621ffd0d-a820-41a9-8102-8b37a10927ee bound to port 6
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: port 6 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/adapters/0/ports/6/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO vpcs_vm.py:376 VPCS "198.16.0.15" [6e7a02e8-e925-4c05-a9f0-0e442cff63e3]: NIO UDP added to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/6e7a02e8-e925-4c05-a9f0-0e442cff63e3/adapters/0/ports/0/nio HTTP/1.1" 201 379 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: NIO udp-1b9b8bf8-3f5c-4e0d-83b9-538aa4ddda6f bound to port 4
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93]: port 4 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/451f9b68-0a39-4975-8f9c-c47d48e7ed93/adapters/0/ports/4/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_hub.py:147 Ethernet hub "198.16.0.0" [291f188c-98a7-4e5e-bfac-e00e19780bbd]: NIO udp-84aff457-4383-43e6-bb9b-1ac950733e1f bound to port 0
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_hub/nodes/291f188c-98a7-4e5e-bfac-e00e19780bbd/adapters/0/ports/0/nio HTTP/1.1" 201 387 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.1" [0dab2800-35cb-4361-884b-2862bcc9bfef]: NIO udp-88738887-2a41-40d2-96ae-9e99ca969421 bound to port 2
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.1" [0dab2800-35cb-4361-884b-2862bcc9bfef]: port 2 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0dab2800-35cb-4361-884b-2862bcc9bfef/adapters/0/ports/2/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_hub.py:147 Ethernet hub "198.16.0.0" [291f188c-98a7-4e5e-bfac-e00e19780bbd]: NIO udp-5fe7dfb2-06aa-456d-a4a1-fccafe62b1ac bound to port 1
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_hub/nodes/291f188c-98a7-4e5e-bfac-e00e19780bbd/adapters/0/ports/1/nio HTTP/1.1" 201 387 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103]: NIO udp-1b8d4a42-96b7-4db5-a93a-ff91849d93cc bound to port 3
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103]: port 3 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/af19e45f-67d3-439a-8b19-b50f30296103/adapters/0/ports/3/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_hub.py:147 Ethernet hub "198.16.0.0" [291f188c-98a7-4e5e-bfac-e00e19780bbd]: NIO udp-3a4f778f-7ecf-40d3-923c-15dc063e0b84 bound to port 2
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_hub/nodes/291f188c-98a7-4e5e-bfac-e00e19780bbd/adapters/0/ports/2/nio HTTP/1.1" 201 387 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ports/udp HTTP/1.1" 201 244 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_switch.py:275 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: NIO udp-7de93170-ea01-448d-9ef8-5e9b0e8a98b0 bound to port 7
2022-05-06 14:09:47 INFO ethernet_switch.py:365 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d]: port 7 set as an access port in VLAN 1
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/adapters/0/ports/7/nio HTTP/1.1" 201 390 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO ethernet_hub.py:147 Ethernet hub "198.16.0.0" [291f188c-98a7-4e5e-bfac-e00e19780bbd]: NIO udp-bbdaa1c1-a09a-4046-b297-070bde2abda5 bound to port 3
2022-05-06 14:09:47 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:39:47 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_hub/nodes/291f188c-98a7-4e5e-bfac-e00e19780bbd/adapters/0/ports/3/nio HTTP/1.1" 201 387 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:46 +0000] "POST /v2/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/open HTTP/1.1" 201 747 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "GET /v2/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/nodes HTTP/1.1" 200 49855 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:47 INFO project_handler.py:272 New client has connected to the notification stream for project ID '86b0b48b-bba8-4986-9eae-8964d865c47a' (WebSocket method)
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "GET /v2/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/links HTTP/1.1" 200 26719 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:09:47 INFO web_log.py:206 ::1 [06/May/2022:08:39:47 +0000] "GET /v2/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/drawings HTTP/1.1" 200 206 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0dab2800-35cb-4361-884b-2862bcc9bfef/start HTTP/1.1" 204 198 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/af19e45f-67d3-439a-8b19-b50f30296103/start HTTP/1.1" 204 198 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/451f9b68-0a39-4975-8f9c-c47d48e7ed93/start HTTP/1.1" 204 198 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/start HTTP/1.1" 204 198 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/635346da-38c1-483d-92bb-3f00cd57af1c/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/af6a6809-6718-4867-8d5f-22d094f254f7/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/e3ef85ee-96c7-4e01-8601-a0e4df1246c7/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/68885b97-1f1a-48a2-b23a-482b60571460/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/71c3a279-3e62-4502-a66f-575a3c1d71a9/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/e2993d66-e411-4303-b6db-8af0aeb31c01/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/8e6346e2-24a5-49bd-9a6f-1de3884ad63a/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/bfa31ea6-fddd-49d7-9888-ff20563e92c1/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/33bc1a19-ff1e-4f57-bd82-4573385cb39b/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/3f495037-4a81-40bd-bcab-e3d67cb4f5e0/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/d21636fc-fa63-4777-9577-b2835249eac8/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/64af328b-55e7-440a-85da-f8fbb25223ba/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/0e72f780-c170-4138-9ea5-b8a1a17a17e3/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/977096cf-ce03-4a78-8849-69e198f875af/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/30827c6b-655c-457f-b522-f27f5dba2fce/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 ERROR route.py:217 Node error detected: VPCSError
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/gns3server/web/route.py", line 198, in control_schema
    await func(request, response)
  File "/usr/lib/python3.10/site-packages/gns3server/handlers/api/compute/vpcs_handler.py", line 160, in start
    await vm.start()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 220, in start
    await self._check_requirements()
  File "/usr/lib/python3.10/site-packages/gns3server/compute/vpcs/vpcs_vm.py", line 110, in _check_requirements
    raise VPCSError("No path to a VPCS executable has been set")
gns3server.compute.vpcs.vpcs_error.VPCSError: No path to a VPCS executable has been set
2022-05-06 14:10:13 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/6e7a02e8-e925-4c05-a9f0-0e442cff63e3/start HTTP/1.1" 409 349 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_hub/nodes/291f188c-98a7-4e5e-bfac-e00e19780bbd/start HTTP/1.1" 204 195 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:13 INFO web_log.py:206 ::1 [06/May/2022:08:40:13 +0000] "POST /v2/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/nodes/start HTTP/1.1" 409 295 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/af19e45f-67d3-439a-8b19-b50f30296103/suspend HTTP/1.1" 204 200 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0dab2800-35cb-4361-884b-2862bcc9bfef/suspend HTTP/1.1" 204 200 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/451f9b68-0a39-4975-8f9c-c47d48e7ed93/suspend HTTP/1.1" 204 200 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/suspend HTTP/1.1" 204 200 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/635346da-38c1-483d-92bb-3f00cd57af1c/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/af6a6809-6718-4867-8d5f-22d094f254f7/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/e3ef85ee-96c7-4e01-8601-a0e4df1246c7/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/71c3a279-3e62-4502-a66f-575a3c1d71a9/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/68885b97-1f1a-48a2-b23a-482b60571460/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/e2993d66-e411-4303-b6db-8af0aeb31c01/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/8e6346e2-24a5-49bd-9a6f-1de3884ad63a/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/bfa31ea6-fddd-49d7-9888-ff20563e92c1/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/33bc1a19-ff1e-4f57-bd82-4573385cb39b/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/d21636fc-fa63-4777-9577-b2835249eac8/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/3f495037-4a81-40bd-bcab-e3d67cb4f5e0/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/64af328b-55e7-440a-85da-f8fbb25223ba/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/0e72f780-c170-4138-9ea5-b8a1a17a17e3/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/977096cf-ce03-4a78-8849-69e198f875af/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/30827c6b-655c-457f-b522-f27f5dba2fce/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_hub/nodes/291f188c-98a7-4e5e-bfac-e00e19780bbd/suspend HTTP/1.1" 204 197 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/6e7a02e8-e925-4c05-a9f0-0e442cff63e3/suspend HTTP/1.1" 204 189 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:24 INFO web_log.py:206 ::1 [06/May/2022:08:40:24 +0000] "POST /v2/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/nodes/suspend HTTP/1.1" 204 166 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:30 INFO project_handler.py:281 Client has disconnected from notification stream for project ID '86b0b48b-bba8-4986-9eae-8964d865c47a' (WebSocket method)
2022-05-06 14:10:30 INFO web_log.py:206 ::1 [06/May/2022:08:40:30 +0000] "POST /v2/projects/load HTTP/1.1" 201 722 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:30 INFO project_handler.py:272 New client has connected to the notification stream for project ID 'dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6' (WebSocket method)
2022-05-06 14:10:30 INFO web_log.py:206 ::1 [06/May/2022:08:40:30 +0000] "GET /v2/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/nodes HTTP/1.1" 200 203 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:30 INFO web_log.py:206 ::1 [06/May/2022:08:40:30 +0000] "GET /v2/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/links HTTP/1.1" 200 203 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:30 INFO web_log.py:206 ::1 [06/May/2022:08:40:30 +0000] "GET /v2/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/drawings HTTP/1.1" 200 206 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:35 INFO project_handler.py:290 Project '86b0b48b-bba8-4986-9eae-8964d865c47a' is automatically closing due to no client listening
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0dab2800-35cb-4361-884b-2862bcc9bfef/stop HTTP/1.1" 204 197 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/451f9b68-0a39-4975-8f9c-c47d48e7ed93/stop HTTP/1.1" 204 197 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/af19e45f-67d3-439a-8b19-b50f30296103/stop HTTP/1.1" 204 197 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_switch/nodes/0040c9ad-955e-44ea-b610-4e9ad87d664d/stop HTTP/1.1" 204 197 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/af6a6809-6718-4867-8d5f-22d094f254f7/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/635346da-38c1-483d-92bb-3f00cd57af1c/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/e3ef85ee-96c7-4e01-8601-a0e4df1246c7/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/71c3a279-3e62-4502-a66f-575a3c1d71a9/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/68885b97-1f1a-48a2-b23a-482b60571460/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/e2993d66-e411-4303-b6db-8af0aeb31c01/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/8e6346e2-24a5-49bd-9a6f-1de3884ad63a/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/bfa31ea6-fddd-49d7-9888-ff20563e92c1/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/33bc1a19-ff1e-4f57-bd82-4573385cb39b/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/d21636fc-fa63-4777-9577-b2835249eac8/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/3f495037-4a81-40bd-bcab-e3d67cb4f5e0/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/64af328b-55e7-440a-85da-f8fbb25223ba/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/0e72f780-c170-4138-9ea5-b8a1a17a17e3/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/977096cf-ce03-4a78-8849-69e198f875af/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/30827c6b-655c-457f-b522-f27f5dba2fce/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/ethernet_hub/nodes/291f188c-98a7-4e5e-bfac-e00e19780bbd/stop HTTP/1.1" 204 194 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/vpcs/nodes/6e7a02e8-e925-4c05-a9f0-0e442cff63e3/stop HTTP/1.1" 204 186 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.25' [8e6346e2-24a5-49bd-9a6f-1de3884ad63a]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.24' [33bc1a19-ff1e-4f57-bd82-4573385cb39b]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.26' [bfa31ea6-fddd-49d7-9888-ff20563e92c1]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.20' [d21636fc-fa63-4777-9577-b2835249eac8]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.6' [e3ef85ee-96c7-4e01-8601-a0e4df1246c7]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.8' [71c3a279-3e62-4502-a66f-575a3c1d71a9]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.15' [6e7a02e8-e925-4c05-a9f0-0e442cff63e3]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.27' [e2993d66-e411-4303-b6db-8af0aeb31c01]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.21' [3f495037-4a81-40bd-bcab-e3d67cb4f5e0]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.17' [0e72f780-c170-4138-9ea5-b8a1a17a17e3]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.2' [af6a6809-6718-4867-8d5f-22d094f254f7]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.19' [64af328b-55e7-440a-85da-f8fbb25223ba]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.7' [68885b97-1f1a-48a2-b23a-482b60571460]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.16' [30827c6b-655c-457f-b522-f27f5dba2fce]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.18' [977096cf-ce03-4a78-8849-69e198f875af]: is closing
2022-05-06 14:10:35 INFO base_node.py:331 VPCS: '198.16.0.3' [635346da-38c1-483d-92bb-3f00cd57af1c]: is closing
2022-05-06 14:10:35 INFO ethernet_switch.py:252 Ethernet switch "198.16.0.1" [0dab2800-35cb-4361-884b-2862bcc9bfef] has been deleted
2022-05-06 14:10:35 INFO hypervisor.py:148 Stopping Dynamips process PID=23355
2022-05-06 14:10:35 INFO ethernet_hub.py:123 Ethernet hub "198.16.0.0" [291f188c-98a7-4e5e-bfac-e00e19780bbd] has been deleted
2022-05-06 14:10:35 INFO hypervisor.py:148 Stopping Dynamips process PID=23419
2022-05-06 14:10:35 INFO ethernet_switch.py:252 Ethernet switch "198.16.0.5" [af19e45f-67d3-439a-8b19-b50f30296103] has been deleted
2022-05-06 14:10:35 INFO hypervisor.py:148 Stopping Dynamips process PID=23387
2022-05-06 14:10:35 INFO ethernet_switch.py:252 Ethernet switch "198.16.0.23" [451f9b68-0a39-4975-8f9c-c47d48e7ed93] has been deleted
2022-05-06 14:10:35 INFO hypervisor.py:148 Stopping Dynamips process PID=23371
2022-05-06 14:10:35 INFO ethernet_switch.py:252 Ethernet switch "198.16.0.14" [0040c9ad-955e-44ea-b610-4e9ad87d664d] has been deleted
2022-05-06 14:10:35 INFO hypervisor.py:148 Stopping Dynamips process PID=23403
2022-05-06 14:10:35 INFO web_log.py:206 ::1 [06/May/2022:08:40:35 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:35 INFO project.py:361 Project 86b0b48b-bba8-4986-9eae-8964d865c47a with path '/home/barbarik/GNS3/projects/aishani' closed
2022-05-06 14:10:35 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:35 +0000] "POST /v2/compute/projects/86b0b48b-bba8-4986-9eae-8964d865c47a/close HTTP/1.1" 204 166 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:39 INFO project.py:78 Project dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6 with path '/home/barbarik/GNS3/projects/lab' created
2022-05-06 14:10:39 WARNING project_manager.py:96 Only 9.20% or less of free disk space detected in "/home/barbarik/GNS3/projects/lab" on "firefly"
2022-05-06 14:10:39 INFO web_log.py:206 ::1 [06/May/2022:08:40:39 +0000] "POST /v2/compute/projects HTTP/1.1" 201 299 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:39 INFO __init__.py:303 Creating new hypervisor localhost:40789 with working directory /home/barbarik/GNS3/projects/lab/project-files/dynamips
2022-05-06 14:10:39 INFO hypervisor.py:127 Starting Dynamips: ['/usr/bin/dynamips', '-N1', '-l', 'dynamips_i6_log.txt', '-H', 'localhost:40789']
2022-05-06 14:10:39 INFO hypervisor.py:129 Dynamips process logging to /home/barbarik/GNS3/projects/lab/project-files/dynamips/dynamips_i6_stdout.txt
2022-05-06 14:10:39 INFO hypervisor.py:136 Dynamips process started PID=24553
2022-05-06 14:10:39 INFO __init__.py:305 Hypervisor localhost:40789 has successfully started
2022-05-06 14:10:40 INFO dynamips_hypervisor.py:92 Connected to Dynamips hypervisor on localhost:40789 after 0.2988 seconds
2022-05-06 14:10:40 INFO ethernet_switch.py:187 Ethernet switch "Switch1" [45a7a12b-ae1d-4a00-a7b9-3e624d92d93a] has been created
2022-05-06 14:10:40 INFO web_log.py:206 127.0.0.1 [06/May/2022:08:40:39 +0000] "POST /v2/compute/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/ethernet_switch/nodes HTTP/1.1" 201 1562 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:40 INFO web_log.py:206 ::1 [06/May/2022:08:40:39 +0000] "POST /v2/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/templates/1966b864-93e7-32d5-965f-001384eec461 HTTP/1.1" 201 4634 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:40 INFO web_log.py:206 ::1 [06/May/2022:08:40:40 +0000] "PUT /v2/compute/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/ethernet_switch/nodes/45a7a12b-ae1d-4a00-a7b9-3e624d92d93a HTTP/1.1" 200 1567 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:10:40 INFO web_log.py:206 ::1 [06/May/2022:08:40:40 +0000] "PUT /v2/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/nodes/45a7a12b-ae1d-4a00-a7b9-3e624d92d93a HTTP/1.1" 200 4706 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:10:40 INFO web_log.py:206 ::1 [06/May/2022:08:40:40 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:11:02 INFO ethernet_switch.py:252 Ethernet switch "Switch1" [45a7a12b-ae1d-4a00-a7b9-3e624d92d93a] has been deleted
2022-05-06 14:11:02 INFO hypervisor.py:148 Stopping Dynamips process PID=24553
2022-05-06 14:11:02 INFO web_log.py:206 ::1 [06/May/2022:08:41:02 +0000] "DELETE /v2/compute/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/ethernet_switch/nodes/45a7a12b-ae1d-4a00-a7b9-3e624d92d93a HTTP/1.1" 204 192 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:11:02 INFO web_log.py:206 ::1 [06/May/2022:08:41:02 +0000] "DELETE /v2/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/nodes/45a7a12b-ae1d-4a00-a7b9-3e624d92d93a HTTP/1.1" 204 168 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:11:02 INFO web_log.py:206 ::1 [06/May/2022:08:41:02 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol 'fortinet.svg', returning default symbol...
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol 'juniper-vqfx.svg', returning default symbol...
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol 'loadbalancer.svg', returning default symbol...
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol 'linux_guest.svg', returning default symbol...
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol 'firefox.svg', returning default symbol...
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol 'cisco-ise.svg', returning default symbol...
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol 'mgmt_station.svg', returning default symbol...
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol '6wind.svg', returning default symbol...
2022-05-06 14:13:07 WARNING symbols.py:134 Could not retrieve symbol 'shieldedtux.png', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'microsoft.svg', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'opennac.png', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'cisco-fmcv.svg', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'securityonion-logo.png', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'steelhead-vcx.png', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'juniper-vmx.svg', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'pan-vm-fw.svg', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'vyos.svg', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'packetfence2.png', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'rpi.png', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'parrotlogo.png', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'mgmt_station_docker.svg', returning default symbol...
2022-05-06 14:13:08 WARNING symbols.py:134 Could not retrieve symbol 'vRIN.svg', returning default symbol...
2022-05-06 14:13:21 INFO web_log.py:206 ::1 [06/May/2022:08:43:21 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:13:35 INFO web_log.py:206 ::1 [06/May/2022:08:43:35 +0000] "GET /v2/computes HTTP/1.1" 200 1022 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:14:37 INFO web_log.py:206 ::1 [06/May/2022:08:44:37 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:14:38 INFO web_log.py:206 ::1 [06/May/2022:08:44:38 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:14:39 INFO web_log.py:206 ::1 [06/May/2022:08:44:39 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:14:40 INFO web_log.py:206 ::1 [06/May/2022:08:44:40 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:14:40 INFO web_log.py:206 ::1 [06/May/2022:08:44:40 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:14:40 INFO web_log.py:206 ::1 [06/May/2022:08:44:40 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:14:40 INFO web_log.py:206 ::1 [06/May/2022:08:44:40 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:14:45 INFO web_log.py:206 ::1 [06/May/2022:08:44:45 +0000] "GET /v2/symbols HTTP/1.1" 200 104894 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:17:16 INFO notification_handler.py:82 Client has disconnected from controller WebSocket
2022-05-06 14:17:16 INFO server_handler.py:53 Start shutting down the server
2022-05-06 14:17:16 INFO project.py:361 Project dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6 with path '/home/barbarik/GNS3/projects/lab' closed
2022-05-06 14:17:16 INFO web_log.py:206 ::1 [06/May/2022:08:47:16 +0000] "POST /v2/compute/projects/dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6/close HTTP/1.1" 204 166 "-" "Python/3.10 aiohttp/3.8.1"
2022-05-06 14:17:16 INFO web_log.py:206 ::1 [06/May/2022:08:47:16 +0000] "POST /v2/shutdown HTTP/1.1" 201 195 "-" "GNS3 QT Client v2.2.31"
2022-05-06 14:17:16 INFO web_server.py:113 Closing 2 websocket connections...
2022-05-06 14:17:16 INFO compute.py:460 Connection closed to compute 'local' WebSocket 'http://localhost:3080/v2/compute/notifications/ws'
2022-05-06 14:17:16 INFO project_handler.py:281 Client has disconnected from notification stream for project ID 'dc3ed8cf-c21e-4d66-bee6-29ab53f39ce6' (WebSocket method)
2022-05-06 14:17:16 INFO notification_handler.py:59 Client has disconnected from compute WebSocket
2022-05-06 14:17:16 INFO __init__.py:138 Controller is stopping
2022-05-06 14:17:16 INFO run.py:272 Remove PID file /home/barbarik/.config/GNS3/2.2/gns3_server.pid
